a = 10
b = 5
c = a+b
d = a-b
e = a*b
f = a/b
print("1st Number =",a)
print("2nd Number =",b)
print(str(a),"+",str(b),"=",c)
print(str(a),"-",str(b),"=",d)
print(str(a),"*",str(b),"=",e)
print(str(a),"/",str(b),"=",f)